project:
  type: website

website:
  title: "MIBE Excel Corner"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        menu:
        - index.qmd
        - Beforewestart.qmd
        - Classroomfiles.qmd
      - text: "Lesson 1"
        menu:
        - "Introduction to Formatting"
        - Lesson1.qmd
        - Practice1a.qmd
        - Practice1b.qmd
        - Practice1c.qmd
        - Practice1d.qmd
      - text: "Lesson 2"
        menu:
        - "Using Functions"
        #- "Coming soon"
        - Lesson2.qmd
        - Practice2a.qmd
        - Practice2b.qmd
        - Practice2c.qmd
        - Practice2d.qmd
        - Practice2e.qmd
      - text: "Lesson 3"
        menu:
        - "Worksheet and Workbook Management"
        - "Coming soon"
      - text: "Lesson 4"
        menu:
        - "Visualize, Sort, and Filter Data"
        - "Coming soon"
      - text: "Lesson 5"
        menu:
        - "Summarize the Data with Pivot Tables"
        - "Coming soon"
      - text: "Lesson 6"
        menu:
        - "Comprehensive Analysis"
        - "Coming soon"
        
format:
  html:
    theme: minty
    toc: true
    toc-depth: 2

editor: visual
