---
title: "Practice 5a - Data import and cleaning"
author: "Dr. Bartosiak"
---

# Practie video 5a

::: {.callout-tip title="Windows" collapse="true"}
{{< video https://youtu.be/QgPjqnfwQpw title="Practice 5a Windows" >}}
:::

::: {.callout-tip title="Mac" collapse="true"}
{{< video https://youtu.be/v_8i4f5o-8w title="Practice 5a Mac" >}}
:::

## Answer key

[Answer key](/_files/keys/key_intromis-5-a_1.xlsx){target="_blank"}

# Instructions

[Starter Workbook](/_files/starters/starter_intromis-5-a.xlsx){target="_blank"}

## Tasks and Steps

1.	Download the text file from: ["text-data-source"](/_site/pizza-sales-data.txt){target="_blank"}.
2.	Download and open the empty starter file.
3.	Import the data in a new Excel workbook. Remember that the file is pipe (|) separated. [Mac](https://support.microsoft.com/en-us/office/import-data-from-a-csv-html-or-text-file-b62efe49-4d5b-4429-b788-e1211b5e90f6) [Win](https://support.microsoft.com/en-us/office/import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba)
4.	Review the data to make sure it was imported correctly. There should be a header with column names for all 9 columns and a total of 3077 rows. With these much data you need to remember your keyboard shortcuts, so you can move efficiently through the data.
5.	Rename Sheet1 as “Pizza Sales Data”.
6.	Format the header (first row) as bold:
o	Set the font size to 16 points
7.	Prevent editing of the Pizza Sales Data worksheet by protecting it. Do not use a password. [Mac](https://support.microsoft.com/en-us/office/protect-a-worksheet-in-mac-9ef52175-aaeb-4471-88d7-acdad93819c5) [Win](https://support.microsoft.com/en-us/office/protect-a-worksheet-3179efdb-1285-4d49-a9c3-f4ca36276de6)
8.	Insert a new worksheet and rename it as “Pizza Sales Calculations”.
9.	Make sure the order is correct. Pizza Sales Data should be the first (leftmost) worksheet and Pizza Sales Calculations should be second.
10.	Copy the data from the Pizza Sales Data worksheet into the Pizza Sales Calculations worksheet. Remember the concept of single source of truth and make sure to use the appropriate paste options to link to the source data rather than replicate it. [Mac](https://support.microsoft.com/en-us/office/paste-options-8ea795b0-87cd-46af-9b59-ed4d8b1669ad) [Win](https://support.microsoft.com/en-us/office/paste-options-8ea795b0-87cd-46af-9b59-ed4d8b1669ad)
11.	Format the header of the Pizza Sales Calculations worksheet to be the same as the header of the Pizza Sales Data worksheet. [Mac](https://support.microsoft.com/en-us/office/copy-cell-formatting-b9fe82ea-c0a0-41de-837b-d2f15dd41ea9) [Win](https://support.microsoft.com/en-us/office/copy-cell-formatting-b9fe82ea-c0a0-41de-837b-d2f15dd41ea9)
12.	Ensure each column is formatted appropriately for its content. DeliveryDistance is in miles so you should format it with two decimals, OrderPlaced, OrderReady and OrderDelivery are dates (use the Long Date format). TotalPrice (No Taxes) should be Accounting.
13.	Make sure all text is visible by resizing the columns appropriately.
14.  Save the file and close it.

------------------------------------------------------------------------

```{=html}
<style>
.disclaimer {
  font-size: 0.8em;
  color: #666;
  border-top: 1px solid #ddd;
  padding-top: 10px;
  margin-top: 20px;
}
</style>
```

```{=html}
<div>
  {{< include footer.html >}}
</div>
```
